version: '3.4'

services:
  reverse-proxy:
    image: traefik:v2.3
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
    labels:
      #Redirect HTTP -> HTTPS
      - "traefik.enable=true"
      - "traefik.http.routers.https-redirect.entrypoints=http"
      - "traefik.http.routers.https-redirect.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.https-redirect.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
    ports:
      - 80:80
      - 443:443
      - 30080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt/live/embedd.ml/cert.pem:/secrets/cert.pem
      - /etc/letsencrypt/live/embedd.ml/privkey.pem:/secrets/key.pem
      - ./certs-traefik.yaml:/etc/traefik/dynamic/certs-traefik.yaml
  api:
    image: piotrgramacki/sma-backend:0.4
    labels:
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.rule=Host(`api-politicians.embedd.ml`)"
      - "traefik.http.services.api-service.loadbalancer.server.port=80"
    environment:
      - CONSUMER_KEY=***
      - CONSUMER_SECRET=***
      - ACCESS_TOKEN_KEY=***
      - ACCESS_TOKEN_SECRET=***
    volumes:
      - ./data/:/app/data/
