version: '3.8'

services:
  api:
    image: piotrgramacki/sma-backend:0.8
    ports:
      - 4000:80
    env_file:
      - env_files/twitter_credentials.env
      - env_files/celery.env
    volumes:
      - ./backend_service/app/:/app/

  tweets-worker:
    image: piotrgramacki/sma-celery:0.1
    command: [celery, --app=tweets.app, worker]
    env_file:
      - env_files/celery.env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8