version: '3.8'

services:
  api:
    image: piotrgramacki/sma-backend:0.8
    ports:
      - 4000:80
    env_file:
      - env_files/twitter_credentials.env
      - env_files/celery.env
    volumes:
      - ./backend_service/app/:/app/

  tweets-worker:
    image: piotrgramacki/sma-celery:tweets
    command: [celery, --app=tweets.app, worker, -Q, tweets]
    env_file:
      - env_files/celery.env
    depends_on:
      - rabbitmq
    volumes:
      - ./celery_service/app:/app/

  embedding-worker:
    image: piotrgramacki/sma-celery:embedding
    command: [celery, --app=embedding.app, worker, -Q, embedding]
    env_file:
      - env_files/celery.env
    depends_on:
      - rabbitmq
    volumes:
    - ./celery_service/app:/app/

  processing-worker:
    image: piotrgramacki/sma-celery:processing
    command: [celery, --app=processing.app, worker, -Q, processing]
    env_file:
      - env_files/celery.env
    depends_on:
      - rabbitmq
    volumes:
    - ./celery_service/app:/app/

  cleaning-worker:
    image: piotrgramacki/sma-celery:processing
    command: [celery, --app=cleaning.app, worker, -Q, cleaning]
    env_file:
      - env_files/celery.env
    depends_on:
      - rabbitmq
      - krnnt
    volumes:
      - ./celery_service/app:/app/

  krnnt:
    image: djstrong/krnnt:1.0.0

  rabbitmq:
    image: rabbitmq:3.8