version: '3.4'

services:
  tweets-worker:
    image: piotrgramacki/sma-celery:tweets
    command: [celery, --app=tweets.app, worker, -Q, tweets]
    environment:
      - CELERY_BROKER_URL=redis://embedd.ml:35672/0
      - CELERY_RESULT_BACKEND=redis://embedd.ml:35672/0
      - TWEETS_LIMIT=1000
